### ISSUE TITLE
Please share the SoC ID!

### ISSUE THREAD

**Issue by apritzel** [Florianclume/hacking_bookeen_notea#1]
Hi Florian,

neat story, sorry to hear that you gave up! In the BSP bootlog of your linux-sunxi wikipage I read:

`android.hardware = sun8iw15p1`

That would mean it's the same SoC as the Allwinner A50, for which we have a user manual, so could create a mainline port (albeit without easy display capabilities quickly).
However BSPs have been lying before, so can you confirm what the SoCID is? Please note that it's not a serial number, but just a 16-bit identifier of the SoC type, as listed in this [Wiki table](https://linux-sunxi.org/Allwinner_SoC_Family#2013_naming_scheme_change) or [here](https://github.com/linux-sunxi/sunxi-tools/blob/master/soc_info.c#L320) in sunxi-fel's table of supported SoCs (list them with `sunxi-fel --list-socs`).

When sunxi-fel lists the right number, we can be sure that the B300 is the same, and could start working on Open Source support for that SoC.
Thanks,
Andre

**Comment by Florianclume** [comment]
Oh dear! You're totally right! I totally forgot that I had censored it after I leaked it here: https://oftc.irclog.whitequark.org/linux-sunxi/2024-10-05
The SoC id is `1755`, sorry again for the inconvenience.

Come back to me if you manage to do anything that might interest me!

Best regards,
Florian

**Comment by apritzel** [comment]
Many thanks, that's exactly the number I was hoping for! And I now see that you actually posted that already, I just didn't connect the dots back then ...
